language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/

env:
  global:
    # SONATYPE_USERNAME
    - secure: "hWt0UzEp9XIk5zTjPbq9gSb9vAJCAZbT7kOpuoa9MztCnShYsQLQm1GLVKn7dEeoRNsTeG9Y0mkXmA6Gi7jed+6Miq2VLeW21pqSodWa6fHejy5QTA1QJ/XLMpyGvuqQaIsay/YlQ0pv7iG6gafIt7Q8adKfERcB7unZf2N1FEpc1AmuQmLZPBhqA1+pO8z1+5sZuuPIFsWKPjKhDBCuJXH09Q6+nPhALOWRWebMvNwgCwaJTpnBOaS7RslDrDogFxTQ6gcd5oEcO+yQM0iC1U8VIArOZPmwzsMMLwJJ1Z3ZNQkEL+ZILnzF3JkdaGl+56GWLpheAYAwgufvU8z8FGC/yIhyxVUUvc1XvjniUinpz/y0/mUp0ACmJrdhZbWnTymghRTDp7JZNxKc/i1Heb4/3SUjY1sEJ/jRU/lB5EXd3ns9WZ7/tQyKCmUuzh6scIQFqvh+7XzZBA6N+elqV0XZNPyhzPKc7ArdnI888Tr1FEIMubsGQ9VycwCIBplUYYMnpu/t5c+KJEBSX4zj4UwFSwiAondihtExrJU5GmM979XrCaL9zvPPwWKKnnHT+T5vJ1feyXk15+Of1XAcBtxY0bCh48d9Xwg9i5DFUjWoIb9PBpcaIqq/NVFxiQ6xNuu+S3K0P0S8flQeitxTzBJMpisdZPCe3PH75kAG4Ng="
    # SONATYPE_PASSWORD
    - secure: "IjNb3LtMR5QC8HEwDQDg0cYdsnojRHx8SJ2dRCHpJdWeWpBWqxF7LdcKod6pTXcWFOY9H3njBCjJHxR1pv8cPJpAaUPtm4fgxZ1CWvKtXub22T797btCO9KQ3qBmatp9Srv2URV310yexs1EKdsfhDDym6jy6hdG6pCSCr7qyBbRXTqcJHlDNvjg9a35DZLdgStYIDqKJwEoJQ9VEWx2336YNr1IP9NtiP/CnmbZIRfr+iBdc+H6gHpSp5xu/SmYixOcwycpcMj4WF9G2dZ1MUvgJiR1Ql52LjE1Vnof8XtXbo69r7KR0tmKOZyi1wAVQavpHLw5jp/9UcW8BEViAXDFdPnllJpwF9GUcj83elmIw3zFaCTt10I+Pw/y76PgU8UB4kBZVedSgZOtBXIeRHPMz7MGhvFP/ffNVg3vDblMjto7MQ+6RZHe5qj807K5sJVeCbBte53HqV1CuZqCft5qtNiHgpfcL0UHQLghJOwg5O8vgaxvfLlNGDcMFLVt6bE0iCKGHiBoPI/ldgdJJ9pVShyg/9TwTJZWVPVco4/EGRJnDjvx4G85w/eYmL1biL4P4dOt5XNU2u8EVw7pBl7Vs3dZZraYbdn4pDoNW7jqHwUpVF9ojFssW/xprBAity9nfUtoGUwNN82RqNgoL7rbI3TXCEiS29okBubZ3Uo="
    # GPG_KEY_NAME
    - secure: "FdJwtQSJa2425Sqyq2bUaROJ8AS7xMBtKyJl3Bl7JKTckmAB4fkLCZAy/HDwHCjIjtzzqzafdkea0GDALGi9KciH3jR8X5c5xLnK6dXRhJPWUsW/lx1LepFimOI6f2puMVUiv4zg7jEBkV7fWrwppDZGz5syYEL9JOtPAH1nW7VeMqmWoGEDJji7DTlcINBB844SXkr/XBELS77La9K/xM2VrT67s3oba2mpWBeHzCvZQCKhQFEw/GnOt3wtMPps5kgvhLPlwge/2tEkEgNO+cz/U2m2T7iS6sgLJ+azIpQjsJy4rRwZlH08TFRD/RMKXIBuBErVcEBnHt69YcBKN0FnttvS5eM/tt+7CXAW/O/w4uj1kbKnXKbeJeLdYdX2ervz22rtmflePLb4ldAo7cQfR08gnnV1jiJzBrlBKK36v5EjvZRj/5DXo/z7El0QO20Kki6xxjsKdTYZw2DURCVnKRKhk2KO3WkKnu+uEIhhzEEd9QeEJWiMJgSW6ntW0vTITaav9GW/kywYaWXskKhoi3FFwLMY9OEOWLWZtLfgvc7l9YMi5boWFNTP8PK6LMNj7AcbgzN7ER+4BTSIQVVaTUpPiFs+GCNQc3+yqb6meF0vDluZaG3WyB2159psvGh8TXovdbnDuHZhzyq4d88LGwhEmDR/3lXPsfN76Gw="
    # GPG_PASSPHRASE
    - secure: "VeSEC0xxEPh7H6hj4aEsyN8b7/nNNlZ3VzzO/fy9Ail2LxSfdouKL9v05zeNN2YvQsQx6suD1mb1PwQ3HxCH7Mkdg6yXxko7vu7CdIwDmrjWygVJEzzut84bqFLHAzQb6FPz51SiOLevkzLunR9asiUzmcZppxn6PSP6uSEk5xfxrHvsLt01JUUHyBkizz7Rp1R+WvFrlKoQ9L2moh1hKRWD5WwCTY3OJzq9Pag2Iw6XsCgoBlTTswiEErstHx4Y6K7DZhF2NppxUPckKkZwWC04WWYcSKgYEkxX+d5JAeZVBYQHERGt/zYfUERYc9XOhuV8tOIZPTOepWneCX0RdO1McuBwnWssvrmm5mZn1GdQ3SJEbaQJ3DumuXIiYKf5pMyg5FI+X41ehA5OTrdTQGrB+6E9krHon5jon2l+mtKAxbbPJkh490GL/tSpZ7CEKpEK0qUR+tEYZU/hK3MfBJaY7Rz/rCaZfiPifKvtFea3SX/XT3hNOOgX/qZ9KPNyuOZw20Pfv6GKvlIOp5E/Tl//F6PgVN0uWwnnGJCfskXJ9QRUpaQ7qO/i0Sca8UK5zmlyekWp+H5jxGLKnun+QaQzTuo4Ale4RCccMgbK5uQZ0C9QoGIioVOJB5AI2sTWewNXCltJAFv9os2It1jt9ansOkG8DMApG6AuMo6RUMg="

script:
  - mvn clean verify -Pcoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./scripts/deploy.sh

branches:
  only:
    - master

notifications:
  email:
    - dbeam-dev+travis-notifications@spotify.com
